### ISSUE TITLE
Issues with installing after 1.8.0

### ISSUE THREAD

**Issue by spidermitch0** [azuravian/playnite-LocalLibrary#51]
Having issues installing any game that is a setup.exe installer.  After a few minutes, this error shows up:

<img width="275" height="102" alt="Image" src="https://github.com/user-attachments/assets/9dea0d0b-b8c9-4fb3-8a0a-cd3d47b65ee4" />

I've attempted multiple different installers, including several folders without any special characters which could be causing something strange.  Furthermore, it seems .rar files still work correctly, so it may not be a pathing issue.

I rolled back to 1.8.1, which also had the same problem, then rolled back to 1.8.0 and it works as expected now.
So it must be an update from 1.8.0 to 1.8.1+
With 1.8.0, I am able to install everything that gave me errors on 1.8.2

Also, I had a clean install of Playnite on a different system entirely and had the same issue with 1.8.2 & 1.8.1.

Let me know whatever logs you need or things I can test to help fix the issue.

**Comment by azuravian** [comment]
I've just published an update 1.8.3.  Please let me know if it's working for you.

**Comment by spidermitch0** [comment]
Unfortunately the problem still persists after updating to 1.8.3.
Again, pointing to \\server\games\FoundGame\setup.exe

Reverting back to 1.8.0 again allowed the game to install.
I guess I should also mention I'm using the ROMS option (not Actions).  Let me know if I can provide any other info to help.

**Comment by azuravian** [comment]
Can you map \\server\games to a drive letter and then set the path as DriveLetter:\\FoundGame\setup.exe and try then?  I want to see if this is an issue specific to UNC paths.

**Comment by spidermitch0** [comment]
Looks like the problem persists after mapping the server to a drive letter.  I took screenshots to document, if u needed it.
Full path is:
`\\servername\Games\Games_2020-2030\Doomsday Paradise (2023) [RePacked]\setup.exe`
and after mapping:
`z:\Games\Games_2020-2030\Doomsday Paradise (2023) [RePacked]\setup.exe`

And as I stated on my first post, I've been trying this each time with a temporary path that goes to `\\servername\temp\setup.exe` (to make sure it's not any symbol / character issue)

<img width="847" height="712" alt="Image" src="https://github.com/user-attachments/assets/b1857460-7695-4048-aaeb-0df698ecbd99" />

<img width="368" height="140" alt="Image" src="https://github.com/user-attachments/assets/927f9f64-5ed8-48ad-8ff2-70acc099026c" />

<img width="846" height="713" alt="Image" src="https://github.com/user-attachments/assets/16ac7748-9831-4ef9-bee8-0a53c3305fff" />

<img width="364" height="162" alt="Image" src="https://github.com/user-attachments/assets/70d63e55-a797-405b-83d5-7a8c3ff901e5" />

**Comment by spidermitch0** [comment]
Also, I just copied the installer files to my local system and changed the path of the Install to:
C:\temp\Doomsday Paradise (2023) [Repack]\setup.exe
And I get the same error.

**Comment by azuravian** [comment]
OK, very interesting that you're getting the same error on your local drive.  Thanks for doing that extra work.  I'm going to add in some extra debug logging and put out a new version.  It won't fix your issue but will hopefully help me track it down.

**Comment by ageekhere** [comment]
I am also having the same issue with exe installers. Any update on finding the issue?

Update see https://github.com/azuravian/playnite-LocalLibrary/issues/49#issuecomment-5305194759
